version: "3.7"

services:
    web:
        build:
            context: .
            dockerfile: ${DOCKER_VOLUME_DOCKER}/Dockerfile
        container_name: ${DOCKER_PROJECT_NAME}
        command: /start
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - ${DOCKER_NGINX_PORT}:80
            - ${DOCKER_NGINX_PORT_SSL}:443
        volumes:
            - ${DOCKER_VOLUME_APP}:/code
            - ${DOCKER_VOLUME_STATIC}:/code/run/static
            - ${DOCKER_VOLUME_MEDIA}:/code/run/media
            - ${DOCKER_VOLUME_DOCKER}:/docker
            - ${DOCKER_VOLUME_APP}/logs:/code/logs
